### PR TITLE
211 add biceps module physiologic monitor

### PR DESCRIPTION
**Pull request by JavierEspina**

### CODE REVIEW

**Review by ToddCooper — CHANGES_REQUESTED** [review]
1. In the generated HTML the PlantUML is not being rendered 
2. Can / should the listing be contained in an [AsciiDoc Collapsible Block](https://docs.asciidoctor.org/asciidoc/latest/blocks/collapsible/) ?

NOTE:  The outline structure of TF-3 has been updated in the master branch.  Rebase this branch on that before merging.

**Comment by d-gregorczyk** [comment]
Don't know what happened to the plantuml export for that particular figure. It works flawlessly in IntelliJ.

**Comment by d-gregorczyk** [comment]
Looks like the Plantuml diagram type that Javier used needs Graphviz to be able to be rendered by Plantuml. Graphviz however is not installed by default, so I added an installation instruction to the CI. Should work now.

**Comment by JavierEspina** [comment]
> 1. In the generated HTML the PlantUML is not being rendered
> 2. Can / should the listing be contained in an [AsciiDoc Collapsible Block](https://docs.asciidoctor.org/asciidoc/latest/blocks/collapsible/) ?
> 
> NOTE: The outline structure of TF-3 has been updated in the master branch. Rebase this branch on that before merging.

Number 1 was solved by David. I've just solved #2. And if all went well - after a lot of hassle - I managed to rebase onto the current Master

**Review by ToddCooper — APPROVED** [review]
Reviewed all files and approved.

**Pull request merged**
