### PR TITLE
49 design for multi page multi file specifications dgr

### PR DESCRIPTION
**Pull request by d-gregorczyk**
This is technical config (github actions) to allow for generation of HTML multipage output.

### CODE REVIEW

**Comment by d-gregorczyk** [comment]
For this PR I literally only need an approval. It's infrastructure only to facilitate compiling the supplement to multipage HTML during the build process.

**Comment by d-gregorczyk** [comment]
@ToddCooper Please approve to merge into master

**Review by ToddCooper — APPROVED** [review]
Reviewed with @d-gregorczyk and approved changes.

**Comment by ToddCooper** [comment]
@d-gregorczyk   Are we done with this PR now?  Can we "close" it?

**Pull request merged**
