### PR TITLE
Resolving IHE Publication edits (v1)

### LINKED ISSUE #2: Repeated word, wording in sentence

### PR DESCRIPTION
**Pull request by ToddCooper**
Editorial issue resolutions from IHE Publications review ( @MaryLJ ), including:

Issue IHE/DEV.SDPi#2 corrected the indicated typos and sentence construction.

### CODE REVIEW

**Review by MaryLJ — APPROVED** [review]
Looks good, thanks.

**Comment by ToddCooper** [comment]
@MaryLJ :  Began looking at the use of "actor" throughout the document ... there were (I removed some) 632 instances of actor, BUT:

1. Many are part of labels (e.g., [[figure_sdpi_p_actor_diagram]] which cannot be changed
2. A few are part of another word like "f**actor** in the use of ..."
3. Some removals made sense, some maybe 
4. Abstract Actor(s) or Grouped Actors etc.  to capitalize or delete or leave?
5. What about Transactions?  If you are capitalizing Actors (or removing) do you need to do the same for Transactions?

All to say, this is editing work that @MaryLJ  will need to do once we have a content-complete draft for Public Comment preparation.

As a result, this PR and the related item are being marked Pre-Public.

**Comment by ToddCooper** [comment]
Review Notes ( @MaryLJ  & @ToddCooper @kenjfuchs  @rhoadsj  ):

1. "PUB TODO:" notes were added in the document to identify specific edits to be made
2. DEV.SDPi repo was created using an IG Publisher template which it does not use BUT might be confusing
* Does it matter?  Will it confuse anyone?  Should / CAN? the repo be deleted and recreated (before migration begins Monday)?  Can we just delete the unneeded files and proceed with the migration?  Can we remove the line that says it was created from an IHE/supplement-template (top left of the repo in browser window)?
* @MaryLJ  asked @JohnMoehrke for guidance, given that he [created the DEV.SDPi repo](https://github.com/IHE/DEV.SDPi)
*  Unnecessary folders & fines can be removed (e.g., Input folder or sushi file)
3. Some sections should be updated per [current template (version 10.6)](https://drive.google.com/drive/u/0/folders/13nsG6u3V--lQgCXCZlt0M73-oRgSXE9q)

**Comment by JohnMoehrke** [comment]
Don't worry about the "generated from IHE/supplement-template".. no harm will come.

**Comment by ToddCooper** [comment]
> Don't worry about the "generated from IHE/supplement-template".. no harm will come.

Thanks!  @d-gregorczyk  will migrate to the new repo early Monday ... Germany time.

**Comment by ToddCooper** [comment]
Migrated changed files to a branch / pull request in DEV.SDPi.

**Pull request closed without merging**
