### PR TITLE
Added HL7 logo to title page (1st pass)

### PR DESCRIPTION
**Pull request by ToddCooper**
First pass at adding logo to title page

### CODE REVIEW

**Comment by ToddCooper** [comment]
@d-gregorczyk :  Could you look at the two logo's and get them side-by-side and the HL7 logo the same size as the IHE logo?

**Comment by ToddCooper** [comment]
@d-gregorczyk - Note that I also added a tag line under the two logos ... perhaps you can incorporate that nicely under a combined logo graphic?  

(And where is that ProtoSDC mug anyway?)

**Comment by d-gregorczyk** [comment]
Done.

**Comment by d-gregorczyk** [comment]
> (And where is that ProtoSDC mug anyway?)

well... I don't have a good excuse :-P

**Review by kenjfuchs — APPROVED** [review]
Looking good!

**Pull request merged**
