### PR TITLE
380 forward declarations as anchors not rendered break the converter

### PR DESCRIPTION
**Pull request by ToddCooper**
#380 Forward Declarations resolved by crafting a labels / acronym table then updating the references.

### CODE REVIEW

**Comment by ToddCooper** [comment]
@d-gregorczyk :  Reviewing the rendering, two issues remain ...

1. Anchors in Figure and Table captions do not get filtered - a 2nd converter filter is needed
2. Links from the new table ("Section Defined in") render crazy long vs. just the final section number (without the section label); is there a way of getting the section number only vs. the entire number and label? 

AND should we add a blank section label "Supplement Acronyms" for these like we do in IEEE or leave it as is?

**Comment by d-gregorczyk** [comment]
1) Anchors in Figure and Table captions do not get filtered - a 2nd converter filter is needed

That shouldn't be a big deal, I'll have a look at it.

2) is there a way of getting the section number only vs. the entire number and label?

Nope, not on short notice. The reference is replace by the source text; and that is the section number including the title text, which is because we perform custom numeration magic. If we enable short-form rendering, it falls back to the original, internal numbering, which is apparently nonsense to use.

We would need another custom magic to iterate the whole content and replace the titles. That's doable for sure, however, anything else but easy.

**Comment by d-gregorczyk** [comment]
Please verify again, the HTML tags in table and figure captions should be gone now.

**Comment by d-gregorczyk** [comment]
Ok, I could not resist... I also fixed the reference links for sections, tables and figures to only contain numbers - however, there are still wonky things in the supplement:

- Appendices are not unique. There are multiple appendices A and B. I guess we have to prefix them with Volume number similar to what we are doing with tables and figure captions.
- Multiple references do not really fit into the references schema. It is no Appendix X, Section X, Table X, or Figure X - sometimes there is something like `<<REF1>>, <<REF2>> and <<REF3>> sections`, which would render to `Section REF1, Section REF2 and Section REF1 sections` - reads odd. I also noticed that many of my references in TF-2 assumed the reference text would be the title text only - which does not hold true, so I have to fix those as well.

See my PR here: #385.

**Comment by ToddCooper** [comment]
> Please verify again, the HTML tags in table and figure captions should be gone now.

@d-gregorczyk  - Verified ... thanks!

**Review by kenjfuchs — APPROVED** [review]
Reviewed and approved.

**Comment by ToddCooper** [comment]
> Reviewed and approved.

@kenjfuchs  -- Good timing!  I literally just did the last tweak about 5 minutes ago ... thanks!  Will complete merge now.

**Pull request merged**
