### PR TITLE
SDPi 1.0 dev internal review v3

### PR DESCRIPTION
**Pull request by ToddCooper**
This "v3" branch completes all SDPi 1.0.0 Comment issue resolution for non-TF-2 sections.  
Note that this includes comments from @AnnaFeiler , @d-gregorczyk , @riechkathrin, @MartinKasp.

### CODE REVIEW

**Review by AnnaFeiler — APPROVED** [review]

**Review by JavierEspina — CHANGES_REQUESTED** [review]
Pending changes of issue #279

**Review by JavierEspina — APPROVED** [review]
All my Vol 0 & Vol 1 comments have been resolved in this PR

**Comment by MartinKasp** [comment]
Some comments from [#289] are sill pending.

**Review by MartinKasp — CHANGES_REQUESTED** [review]
Some comments from [#289] are still pending.

If we do not address all comments, we should harvest the low hanging fruits, e.g., removing the last 7 from "(See [ISO/IEEE 11073-10207:2017]7)" in Appendix D.

**Review by MartinKasp — COMMENTED** [review]
Some aspects are still unresolved and will be discussed later. Additionally, I added two minor commits.

**Review by MartinKasp — APPROVED** [review]

**Comment by ToddCooper** [comment]
Thanks @MartinKasp  - hopefully the unresolved aspects to be discussed later are captured in separate issue tickets so we can track those.  Are they issues to be resolved during the Public Comment period?  1.x?  both?  Thanks.

**Pull request merged**
